$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: aml-training-cli
version: 0.1.0
description: Environment for CNN training component with TensorFlow
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
conda_file: training-conda.yaml
